.TH 
.BR manatee-adm (1) 
\-\- Administration tools for Manatee
.SH SYNOPSIS
.PP
\fB\fCmanatee\-adm [OPTIONS] COMMAND [ARGS...]\fR
.SH DESCRIPTION
.PP
The \fB\fCmanatee\-adm\fR command is used to administer a Manatee shard.
.SH COMMANDS
.SS status [\-hs] \-z
.PP
Display the status of the current manatee shard. By default, the status for
every shard is returned.
.PP
\-h, \-\-help
    Displays a help message.
.PP
\-s, \-\-shard shard
    Display status for the specified shard only.
.PP
\-z, \-\-zk Zookeeper url
    Zookeeper url (such as \fB\fC10.0.1.1:2181\fR)
.PP
The output is a JSON object which encapsulates the state of the Manatee shard.
Each peer in the shard is denoted by its role in the shard, which will be
either \fB\fCprimary\fR, \fB\fCsync\fR, or \fB\fCasync\fR\&. If there are greater than 3 peers in the
shard, each additional peer will be denoted \fB\fCasync\-n\fR, where n is a
monotonically increasing integer starting at 1.
.PP
The \fB\fCrepl\fR field contains postgresql replication information of the next peer
in the shard. On the primary, this would be the \fB\fCsync\fR peer, and on the \fB\fCsync\fR
this would be the \fB\fCasync\fR peer.
.PP
.RS
.nf
"1.moray.emy\-10.joyent.us": {
  "primary": {
    "zoneId": "31f40985\-9578\-48b1\-a92c\-062d1329008b",
    "ip": "172.27.10.242",
    "pgUrl": "tcp://postgres@172.27.10.242:5432/postgres",
    "repl": {
      "pid": 41435,
      "usesysid": 10,
      "usename": "postgres",
      "application_name": "tcp://postgres@172.27.10.238:5432/postgres",
      "client_addr": "172.27.10.238",
      "client_hostname": "",
      "client_port": 62784,
      "backend_start": "2014\-08\-20T00:22:07.802Z",
      "state": "streaming",
      "sent_location": "0/177D7C0",
      "write_location": "0/177D7C0",
      "flush_location": "0/177D7C0",
      "replay_location": "0/177D7C0",
      "sync_priority": 1,
      "sync_state": "sync"
    }
  },
  "sync": {
    "zoneId": "5d5b386a\-29ff\-410b\-80ae\-a63f74ced656",
    "ip": "172.27.10.238",
    "pgUrl": "tcp://postgres@172.27.10.238:5432/postgres",
    "repl": {
      "pid": 41417,
      "usesysid": 10,
      "usename": "postgres",
      "application_name": "tcp://postgres@172.27.10.254:5432/postgres",
      "client_addr": "172.27.10.254",
      "client_hostname": "",
      "client_port": 36209,
      "backend_start": "2014\-08\-20T00:22:02.350Z",
      "state": "streaming",
      "sent_location": "0/177D7C0",
      "write_location": "0/177D7C0",
      "flush_location": "0/177D7C0",
      "replay_location": "0/177D7C0",
      "sync_priority": 0,
      "sync_state": "async"
    }
  },
  "async": {
    "zoneId": "c4f07ca7\-7249\-463e\-b7e3\-e9e8b49b4535",
    "ip": "172.27.10.254",
    "pgUrl": "tcp://postgres@172.27.10.254:5432/postgres",
    "repl": {},
    "lag": {
      "time_lag": null
    }
  }
}
.fi
.RE
.SS clear [\-h] \-sz
.PP
Clear the shard from safe mode.
.PP
\-h, \-\-help
    Displays a help message.
.PP
\-s, \-\-shard shard
    Shard name.
.PP
\-z, \-\-zk Zookeeper url
    Zookeeper url (such as \fB\fC10.0.1.1:2181\fR)
.SS history [OPTIONS...]
.PP
Display the history of Manatee flips.
.PP
\-h, \-\-help
    Displays a help message.
.PP
\-s, \-\-shard shard
    Shard name.
.PP
\-z, \-\-zk Zookeeper url
    Zookeeper url (such as \fB\fC10.0.1.1:2181\fR)
.PP
The output is newline separated JSON where each line is a state transition in
the shard, e.g. Leader flip, new peer in shard.
.PP
.RS
.nf
{"time":"1406081535329","date":"2014\-07\-23T02:12:15.329Z","ip":"10.1.0.144:5432","action":"AssumeLeader","role":"Leader","master":"","slave":"","zkSeq":"0000000066"}
{"time":"1406081648474","date":"2014\-07\-23T02:14:08.474Z","ip":"10.1.0.144:5432","action":"NewStandby","role":"leader","master":"","slave":"10.1.0.139:5432","zkSeq":"0000000067"}
{"time":"1406081648908","date":"2014\-07\-23T02:14:08.908Z","ip":"10.1.0.139:5432","action":"NewLeader","role":"Standby","master":"10.1.0.144:5432","slave":"","zkSeq":"0000000068"}
{"time":"1406081715610","date":"2014\-07\-23T02:15:15.610Z","ip":"10.1.0.140:5432","action":"NewLeader","role":"Standby","master":"10.1.0.139:5432","slave":"","zkSeq":"0000000069"}
{"time":"1406081764623","date":"2014\-07\-23T02:16:04.623Z","ip":"10.1.0.139:5432","action":"AssumeLeader","role":"Leader","master":"","slave":"10.1.0.140:5432","zkSeq":"0000000070"}
{"time":"1406081827174","date":"2014\-07\-23T02:17:07.174Z","ip":"10.1.0.144:5432","action":"NewLeader","role":"Standby","master":"10.1.0.140:5432","slave":"","zkSeq":"0000000071"}
{"time":"1406153586656","date":"2014\-07\-23T22:13:06.656Z","ip":"10.1.0.139:5432","action":"AssumeLeader","role":"Leader","master":"","slave":"","zkSeq":"0000000072"}
{"time":"1406153590231","date":"2014\-07\-23T22:13:10.231Z","ip":"10.1.0.140:5432","action":"NewLeader","role":"Standby","master":"10.1.0.139:5432","slave":"","zkSeq":"0000000073"}
{"time":"1406153590730","date":"2014\-07\-23T22:13:10.730Z","ip":"10.1.0.139:5432","action":"NewStandby","role":"leader","master":"","slave":"10.1.0.140:5432","zkSeq":"0000000074"}
{"time":"1406153600755","date":"2014\-07\-23T22:13:20.755Z","ip":"10.1.0.144:5432","action":"NewLeader","role":"Standby","master":"10.1.0.140:5432","slave":"","zkSeq":"0000000075"}
{"time":"1406154642830","date":"2014\-07\-23T22:30:42.830Z","ip":"10.1.0.140:5432","action":"AssumeLeader","role":"Leader","master":"","slave":"10.1.0.144:5432","zkSeq":"0000000076"}
{"time":"1406154746424","date":"2014\-07\-23T22:32:26.424Z","ip":"10.1.0.139:5432","action":"NewLeader","role":"Standby","master":"10.1.0.144:5432","slave":"","zkSeq":"0000000077"}
{"time":"1406275024079","date":"2014\-07\-25T07:57:04.079Z","ip":"10.1.0.140:5432","action":"NewStandby","role":"leader","master":"","slave":"10.1.0.139:5432","zkSeq":"0000000078"}
{"time":"1406275024298","date":"2014\-07\-25T07:57:04.298Z","ip":"10.1.0.139:5432","action":"NewLeader","role":"Standby","master":"10.1.0.140:5432","slave":"","zkSeq":"0000000079"}
{"time":"1406275032166","date":"2014\-07\-25T07:57:12.166Z","ip":"10.1.0.144:5432","action":"NewLeader","role":"Standby","master":"10.1.0.139:5432","slave":"","zkSeq":"0000000080"}
.fi
.RE
.PP
Each line contains the following fields.
.RS
.IP \(bu 2
\fB\fCtime\fR MS since epoch of the transition event.
.IP \(bu 2
\fB\fCdate\fR Time in UTC of the transition event.
.IP \(bu 2
\fB\fCip\fR IP address of the peer.
.IP \(bu 2
\fB\fCaction\fR Transition event type, one of
.RS
.IP \(bu 2
\fB\fCAssumeLeader\fR, the peer has become the primary of this shard.
.IP \(bu 2
\fB\fCNewLeader\fR, the peer has a new leader it's replicating from.
.IP \(bu 2
\fB\fCNewStandby\fR, the peer has a new standby it's replicating to.
.IP \(bu 2
\fB\fCExpiredStandby\fR, the peer's current standby has expired from the shard.
.RE
.IP \(bu 2
\fB\fCrole\fR Current role of the peer, one of \fB\fCLeader\fR or \fB\fCStandby\fR\&. The primary of
the shard will be \fB\fCLeader\fR, and all other peers will be \fB\fCStandby\fR\&.
.IP \(bu 2
\fB\fCmaster\fR Peer we are replicating from.
.IP \(bu 2
\fB\fCslave\fR Peer we are replicating to.
.IP \(bu 2
\fB\fCzkSeq\fR Internal tracker of the number of state transitions.
.RE
.SS promote [\-h] \-c
.PP
Promote the current peer to the primary of the shard.
.PP
\-h, \-\-help
    Displays a help message.
\-c, \-\-config manatee sitter config
    Path to Manatee sitter config. (such as
    \fB\fC/opt/smartdc/manatee/etc/sitter.cfg\fR)
.SS rebuild [\-hf] \-c
.PP
Rebuild the current peer. In the event of data corruption on the peer, this
command will attempt to rebuild this peer. It will first rollback the current
zfs snapshot and attempt to replicate from its leader. Failing that, a full
rebuild will be performed by receiving the full zfs snapshot from its leader.
.PP
\-h, \-\-help
    Displays a help message.
\-c, \-\-config manatee sitter config
    Path to Manatee sitter config. (such as
    \fB\fC/opt/smartdc/manatee/etc/sitter.cfg\fR)
\-f, \-\-full
    Skip rolling back to the snapshot and do a full rebuild.
.SS check\-lock [\-h] \-pz
.PP
Check the existence of a lock path in Zookeeper. Returns 1 if the lock exists,
0 if it doesn't.
.PP
\-h, \-\-help
    Displays a help message.
.PP
\-p, \-\-path lock path
    Lock path in Zookeeper. (such as \fB\fC/my_special_lock\fR)
.PP
\-z, \-\-zk Zookeeper url
    Zookeeper url (such as \fB\fC10.0.1.1:2181\fR)
.SH ENVIRONMENT
.PP
\fB\fCZK_IPS\fR
    In place of \fB\fC\-z, \-\-zookeeper\fR
.PP
\fB\fCSHARD\fR
    In place of \fB\fC\-s, \-\-shard\fR
.PP
\fB\fCMANATEE_SITTER_CONFIG\fR
    In place of \fB\fC\-c, \-\-config\fR
.PP
\fB\fCLOG_LEVEL\fR
    Sets the node\-bunyan logging level. Defaults to fatal.
.SH COPYRIGHT
.PP
Copyright (c) 2014 Joyent Inc., All rights reserverd.
